Repository jupyter-server/jupyter_releaser, pull requests merged in 2021-05, with the labels that each got.

#12 Pre-release clean up
  .github/actions/draft-changelog/action.yml
  .github/actions/draft-release/action.yml
  .github/actions/publish-release/action.yml
  .github/workflows/draft-changelog.yml
  .github/workflows/draft-release.yml
  .github/workflows/publish-release.yml
  .gitignore
  jupyter_releaser/changelog.py
  jupyter_releaser/lib.py
  jupyter_releaser/tests/test_functions.py
Labels: maintenance

#13 More Cleanup
  .github/workflows/check-release.yml
  .github/workflows/draft-changelog.yml
  .github/workflows/draft-release.yml
  .github/workflows/publish-release.yml
  jupyter_releaser/lib.py
  jupyter_releaser/tests/test_cli.py
Labels: bug

#14 Add Release Screenshots to Documentation
  README.md
  media/draft_changelog_next_step.png
  media/draft_changelog_pr.png
  media/draft_changelog_workflow.png
  media/draft_github_release.png
  media/draft_release_next_step.png
  media/draft_release_workflow.png
  media/final_github_release.png
  media/publish_release_next_step.png
  media/publish_release_workflow.png
Labels: documentation

#16 Prep for PyPI Release
  .github/workflows/publish-release.yml
  README.md
  jupyter_releaser/lib.py
  jupyter_releaser/npm.py
  jupyter_releaser/python.py
Labels: documentation, enhancement

#17 Add forwardport pr screenshot and update publish release screenshot
  README.md
  media/forwardport_pr.png
  media/publish_release_workflow.png
Labels: documentation

#18 Use raw GitHub Links
  README.md
Labels: documentation

#20 Add Support for Since Parameter
  .github/actions/draft-changelog/action.yml
  .github/actions/draft-release/action.yml
  .github/workflows/draft-changelog.yml
  .github/workflows/draft-release.yml
  README.md
  jupyter_releaser/changelog.py
  jupyter_releaser/cli.py
  jupyter_releaser/lib.py
  jupyter_releaser/tests/test_cli.py
Labels: enhancement

#21 Restore 0.1.0 Changelog entry
  CHANGELOG.md
Labels: documentation

#22 Automated Changelog Entry for 0.1.1 on master
  CHANGELOG.md
Labels: documentation

#23 More Cleanup
  jupyter_releaser/changelog.py
  jupyter_releaser/lib.py
Labels: bug

#24 Automated Changelog Entry for 0.1.2 on master
  CHANGELOG.md
Labels: documentation

#25 Fix Check Release for NPM-Only Packages
  .github/actions/check-release/action.yml
Labels: bug

#26 Automated Changelog Entry for 0.1.3 on master
  CHANGELOG.md
Labels: documentation

#27 More Cleanup in Preparation for Usage with Lumino
  jupyter_releaser/changelog.py
  jupyter_releaser/cli.py
  jupyter_releaser/lib.py
  jupyter_releaser/npm.py
  jupyter_releaser/tests/conftest.py
  jupyter_releaser/tests/test_functions.py
  setup.cfg
Labels: maintenance

#28 Automated Changelog Entry for 0.1.4 on master
  CHANGELOG.md
Labels: documentation

#29 More Changes Needed to Support Lumino
  jupyter_releaser/cli.py
  jupyter_releaser/npm.py
  jupyter_releaser/tests/conftest.py
  jupyter_releaser/tests/test_cli.py
Labels: maintenance

#30 Automated Changelog Entry for 0.1.5 on master
  CHANGELOG.md
Labels: documentation

#31 Properly install NPM Packages
  jupyter_releaser/lib.py
  jupyter_releaser/util.py
Labels: maintenance

#33 Automated Changelog Entry for 0.1.6 on master
  CHANGELOG.md
Labels: documentation
