Repository jupyter-server/jupyter_releaser, pull requests merged in 2021-10, with the labels that each got.

#178 Automated Changelog Entry for 0.7.6 on master
  CHANGELOG.md
Labels: documentation

#183 Automated Changelog Entry for 0.9.0 on master
  CHANGELOG.md
Labels: documentation

#186 Clarify scopes needed for admin token
  docs/source/get_started/making_first_release.md
Labels: documentation

#187 Make all of the actions use v1 tag internally
  .github/actions/draft-changelog/action.yml
  .github/actions/draft-release/action.yml
  .github/actions/publish-release/action.yml
Labels: bug

#192 Skip branch setup on publish
  jupyter_releaser/actions/publish_release.py
Labels: bug

#193 Automated Changelog Entry for 0.9.4 on master
  CHANGELOG.md
Labels: documentation

#194 Clean up actions and workflows
  .github/actions/draft-release/action.yml
  .github/actions/publish-release/action.yml
  .github/workflows/draft-changelog.yml
  .github/workflows/draft-release.yml
  .github/workflows/full-release.yml
  .github/workflows/generate-changelog.yml
  .github/workflows/test.yml
Labels: maintenance
