Repository jupyter-server/jupyter_releaser, pull requests merged in 2021-09, with the labels that each got.

#128 Clean up NPM Package Handling
  jupyter_releaser/npm.py
Labels: maintenance

#129 Automated Changelog Entry for 0.5.2 on master
  CHANGELOG.md
Labels: documentation

#130 Remove "Release" from the GitHub Release title
  jupyter_releaser/lib.py
Labels: maintenance

#132 Quieter Output Again
  jupyter_releaser/lib.py
  jupyter_releaser/npm.py
  jupyter_releaser/python.py
  jupyter_releaser/tests/conftest.py
  jupyter_releaser/tests/util.py
  jupyter_releaser/util.py
Labels: maintenance

#134 Add JSON Schema for Config
  MANIFEST.in
  jupyter_releaser/schema.json
  jupyter_releaser/util.py
  setup.cfg
Labels: maintenance

#136 Automated Changelog Entry for 0.6.0 on master
  CHANGELOG.md
Labels: documentation

#137 Fix handling of releaser config in multiple files
  jupyter_releaser/util.py
Labels: maintenance

#138 Use `importlib_resources` to read `schema.json`
  jupyter_releaser/util.py
  setup.cfg
Labels: bug

#140 Read the schema on import
  jupyter_releaser/util.py
Labels: bug

#141 Automated Changelog Entry for 0.6.1 on master
  CHANGELOG.md
Labels: documentation

#143 Read npm versions before `git checkout -- .`
  jupyter_releaser/lib.py
Labels: bug

#144 Automated Changelog Entry for 0.6.2 on master
  CHANGELOG.md
Labels: documentation

#145 Make tag name configurable
  jupyter_releaser/cli.py
  jupyter_releaser/lib.py
  jupyter_releaser/tests/test_cli.py
Labels: enhancement

#146 Add support for PYPI token map
  .github/workflows/publish-release.yml
  README.md
  jupyter_releaser/actions/publish_release.py
Labels: enhancement

#147 Add Since Last Stable Option for Changelog
  .github/actions/draft-changelog/action.yml
  .github/actions/draft-release/action.yml
  .github/workflows/draft-changelog.yml
  .github/workflows/draft-release.yml
  jupyter_releaser/changelog.py
  jupyter_releaser/cli.py
  jupyter_releaser/lib.py
  jupyter_releaser/tests/test_cli.py
  jupyter_releaser/tests/test_functions.py
Labels: enhancement

#149 Enable Auto Publish
  .github/workflows/autopublish-release.yml
  .github/workflows/draft-release.yml
Labels: enhancement

#152 Move registry options to settings
  .github/workflows/publish-release.yml
  jupyter_releaser/cli.py
  jupyter_releaser/lib.py
  jupyter_releaser/tests/test_cli.py
Labels: enhancement

#151 Fix auto publish workflow indent
  .github/workflows/autopublish-release.yml
Labels: bug

#155 Fix handling of PYPI token map
  jupyter_releaser/actions/publish_release.py
Labels: bug

#156 Automated Changelog Entry for 0.7.1 on master
  CHANGELOG.md
Labels: documentation

#157 Fix typo in the draft release action
  .github/actions/draft-release/action.yml
Labels: bug

#158 Automated Changelog Entry for 0.7.1 on master
  CHANGELOG.md
Labels: documentation

#159 Publish Fixes
  jupyter_releaser/actions/publish_release.py
  jupyter_releaser/util.py
Labels: bug

#160 Automated Changelog Entry for 0.7.2 on master
  CHANGELOG.md
Labels: documentation

#162 Automated Changelog Entry for 0.7.3 on master
  CHANGELOG.md
Labels: documentation

#163 Fix Handling of Since Last Stable
  jupyter_releaser/actions/draft_changelog.py
  jupyter_releaser/actions/draft_release.py
  jupyter_releaser/changelog.py
  jupyter_releaser/util.py
Labels: bug

#164 Automated Changelog Entry for 0.7.4 on master
  CHANGELOG.md
Labels: documentation

#165 Document uploading release assets as artifacts
  README.md
Labels: documentation

#166 Add Sphinx Docs
  .github/workflows/test.yml
  MANIFEST.in
  docs/Makefile
  docs/environment.yml
  docs/make.bat
  docs/source/conf.py
  docs/source/index.rst
  pyproject.toml
  readthedocs.yml
Labels: documentation

#171 Reorganize docs
  .gitignore
  README.md
  docs/source/background/index.rst
  docs/source/background/theory.md
  docs/source/conf.py
  docs/source/get_started/generate_changelog.md
  docs/source/get_started/index.rst
  docs/source/get_started/making_first_release.md
  docs/source/how_to_guides/convert_repo.md
  docs/source/how_to_guides/index.rst
  docs/source/how_to_guides/maintain_fork.md
  docs/source/how_to_guides/write_config.md
  docs/source/images/draft_changelog.png
  docs/source/images/draft_changelog_next_step.png
  docs/source/images/draft_changelog_pr.png
  docs/source/images/draft_github_release.png
  docs/source/images/draft_release.png
  docs/source/images/draft_release_next_step.png
  docs/source/images/final_github_release.png
  docs/source/images/fork_fetch.png
  docs/source/images/generate_changelog.png
  docs/source/images/publish_release.png
  docs/source/images/publish_release_next_step.png
  docs/source/index.rst
  docs/source/reference/api_docs.rst
  docs/source/reference/configuration.md
  docs/source/reference/faq.md
  docs/source/reference/index.rst
  docs/source/reference/releaser_cli.md
  media/draft_changelog_pr.png
  media/draft_changelog_workflow.png
  media/draft_release_workflow.png
  media/publish_release_workflow.png
Labels: documentation

#172 Add generated docs and logos
  docs/environment.yml
  docs/source/_static/custom.css
  docs/source/_static/images/logo/favicon.svg
  docs/source/_static/images/logo/logo.svg
  docs/source/conf.py
  docs/source/get_started/making_first_release.md
  docs/source/how_to_guides/write_config.md
  docs/source/reference/api_docs.rst
  docs/source/reference/releaser_cli.md
  docs/source/reference/releaser_cli.rst
Labels: documentation

#173 Debug token map handling
  jupyter_releaser/python.py
Labels: bug

#174 Automated Changelog Entry for 0.7.5 on master
  CHANGELOG.md
Labels: documentation
