Repository jupyter-server/jupyter_releaser, pull requests merged in 2021-04, with the labels that each got.

#1 Clean Up Permissions
  .github/workflows/cancel.yml
  .github/workflows/check-release.yml
  .github/workflows/draft-changelog.yml
  .github/workflows/draft-release.yml
  .github/workflows/publish-release.yml
  README.md
  pyproject.toml
Labels: maintenance

#4 Edit README for usability
  README.md
Labels: documentation

#8 Use Local PyPI Server for Dry Run
  .github/workflows/check-release.yml
  .github/workflows/draft-changelog.yml
  .github/workflows/draft-release.yml
  .github/workflows/publish-release.yml
  .github/workflows/test.yml
  README.md
  jupyter_releaser/actions/publish_release.py
  jupyter_releaser/cli.py
  jupyter_releaser/lib.py
  jupyter_releaser/tests/test_cli.py
  jupyter_releaser/util.py
  setup.cfg
Labels: enhancement

#10 Allow Check Release to be Run on Fork PRs
  .github/actions/check-release/action.yml
  .github/actions/draft-changelog/action.yml
  .github/actions/draft-release/action.yml
  .github/workflows/check-release.yml
  jupyter_releaser/actions/publish_release.py
  jupyter_releaser/changelog.py
  jupyter_releaser/cli.py
  jupyter_releaser/lib.py
  jupyter_releaser/tests/test_cli.py
  jupyter_releaser/tests/test_functions.py
Labels: maintenance

#11 Add missing to install from upstream repo
  .github/actions/check-release/action.yml
Labels: bug
