Repository jupyter-server/jupyter_releaser, pull requests merged in 2021-08, with the labels that each got.

#96 Automated Changelog Entry for 0.3.4 on master
  CHANGELOG.md
Labels: documentation

#97 Add an action for check-links
  .github/actions/check-links/action.yml
  .github/workflows/check-release.yml
  .github/workflows/test.yml
  jupyter_releaser/cli.py
  pyproject.toml
Labels: enhancement

#98 Automated Changelog Entry for 0.4.0 on master
  CHANGELOG.md
Labels: documentation

#99 Clean up build output
  .github/actions/check-links/action.yml
  .github/actions/check-release/action.yml
  jupyter_releaser/actions/draft_release.py
  jupyter_releaser/lib.py
  jupyter_releaser/python.py
  jupyter_releaser/tests/test_cli.py
  jupyter_releaser/util.py
Labels: maintenance

#100 Fix up hook handling
  .github/actions/check-release/action.yml
  README.md
  jupyter_releaser/cli.py
  jupyter_releaser/lib.py
  jupyter_releaser/tests/conftest.py
  jupyter_releaser/tests/test_cli.py
  jupyter_releaser/tests/test_functions.py
  jupyter_releaser/tests/util.py
  jupyter_releaser/util.py
Labels: bug

#102 General code base clean up
  .github/actions/check-release/action.yml
  .pre-commit-config.yaml
  jupyter_releaser/changelog.py
  jupyter_releaser/lib.py
  jupyter_releaser/tests/conftest.py
  jupyter_releaser/tests/test_cli.py
  jupyter_releaser/tests/test_functions.py
  jupyter_releaser/util.py
Labels: maintenance

#103 Automated Changelog Entry for 0.4.2 on master
  CHANGELOG.md
Labels: documentation

#105 Automated Changelog Entry for 0.4.3 on master
  CHANGELOG.md
Labels: documentation

#106 Add Generate Changelog Workflow
  .github/workflows/generate-changelog.yml
  .github/workflows/test.yml
  jupyter_releaser/actions/generate-changelog.py
  jupyter_releaser/changelog.py
Labels: enhancement

#107 More Cleanup
  jupyter_releaser/changelog.py
  jupyter_releaser/lib.py
  jupyter_releaser/npm.py
  jupyter_releaser/util.py
Labels: bug

#108 More Cleanup
  .github/workflows/check-release.yml
  jupyter_releaser/changelog.py
  jupyter_releaser/lib.py
  jupyter_releaser/npm.py
  jupyter_releaser/tests/test_cli.py
  jupyter_releaser/tests/test_functions.py
Labels: maintenance

#109 Automated Changelog Entry for 0.4.4 on master
  CHANGELOG.md
Labels: documentation

#110 Fix handling of "since" parameter
  jupyter_releaser/actions/draft_release.py
Labels: bug

#111 Automated Changelog Entry for 0.4.4 on master
  CHANGELOG.md
Labels: documentation

#112 Fix Create Changelog Action
  jupyter_releaser/actions/draft_changelog.py
  jupyter_releaser/actions/draft_release.py
Labels: bug

#113 Automated Changelog Entry for 0.4.5 on master
  CHANGELOG.md
Labels: documentation

#114 Fix branch name used in CI
  .github/workflows/test.yml
Labels: maintenance

#115 Allow to set commit message
  jupyter_releaser/cli.py
  jupyter_releaser/lib.py
  jupyter_releaser/tests/test_cli.py
  jupyter_releaser/util.py
Labels: enhancement

#116 Cleanup
  .github/workflows/generate-changelog.yml
  .github/workflows/test.yml
  jupyter_releaser/actions/draft_changelog.py
  jupyter_releaser/actions/draft_release.py
  jupyter_releaser/actions/generate-changelog.py
  jupyter_releaser/changelog.py
  jupyter_releaser/cli.py
  jupyter_releaser/lib.py
  jupyter_releaser/tests/test_functions.py
Labels: bug

#117 Automated Changelog Entry for 0.4.6 on master
  CHANGELOG.md
Labels: documentation

#118 Restore capture of since parameter
  jupyter_releaser/actions/draft_changelog.py
  jupyter_releaser/actions/draft_release.py
Labels: bug

#120 Fix usage of since parameter
  .github/workflows/test.yml
  jupyter_releaser/changelog.py
  jupyter_releaser/tests/test_functions.py
Labels: bug

#121 Automated Changelog Entry for 0.4.7 on master
  CHANGELOG.md
Labels: documentation

#122 Fix Extract Release Config and Npm Config Handling
  jupyter_releaser/lib.py
  jupyter_releaser/npm.py
  jupyter_releaser/tests/test_functions.py
Labels: bug

#123 Automated Changelog Entry for 0.5.0 on master
  CHANGELOG.md
Labels: documentation
