Repository jupyter-server/jupyter_releaser, pull requests merged in 2021-11, with the labels that each got.

#205 Allow for a single private package
  jupyter_releaser/util.py
Labels: enhancement

#206 Automated Changelog Entry for 0.9.6 on master
  CHANGELOG.md
Labels: documentation

#207 Allow publish with no assets
  jupyter_releaser/lib.py
  jupyter_releaser/tests/test_cli.py
Labels: enhancement

#208 Automated Changelog Entry for 0.9.7 on master
  CHANGELOG.md
Labels: documentation

#209 Enforce labels on PRs
  .github/workflows/enforce-label.yml
Labels: maintenance

#201 Fix multi python package publishing
  docs/source/get_started/making_first_release.md
  docs/source/how_to_guides/convert_repo.md
  jupyter_releaser/cli.py
  jupyter_releaser/lib.py
Labels: bug

#210 Automated Changelog Entry for 0.9.8 on master
  CHANGELOG.md
Labels: documentation

#211 Remove empty documentation entry
  jupyter_releaser/changelog.py
Labels: enhancement

#214 Cleanup Docs and Base Setup Action
  .github/actions/common/action.yml
  README.md
  docs/source/how_to_guides/convert_repo.md
Labels: documentation, maintenance

#216 Improve Python multi-package handling
  jupyter_releaser/lib.py
Labels: enhancement
