Repository jupyter-server/jupyter_releaser, pull requests merged in 2021-07, with the labels that each got.

#51 Handle missing version from package.json in `get_version`
  jupyter_releaser/util.py
Labels: enhancement

#52 Automated Changelog Entry for 0.1.11 on master
  CHANGELOG.md
Labels: documentation

#53 Fix Handling of Workspace Packages
  jupyter_releaser/npm.py
Labels: bug

#54 More fixups
  jupyter_releaser/cli.py
  jupyter_releaser/lib.py
  jupyter_releaser/npm.py
  jupyter_releaser/tests/test_cli.py
Labels: bug

#55 Automated Changelog Entry for 0.1.12 on master
  CHANGELOG.md
Labels: documentation

#56 Fix handling of workspace paths
  jupyter_releaser/npm.py
Labels: bug

#57 Fix handling of default version bump
  .github/actions/check-release/action.yml
  jupyter_releaser/cli.py
  jupyter_releaser/util.py
Labels: bug

#59 Fix typo
  jupyter_releaser/util.py
Labels: bug

#60 Automated Changelog Entry for 0.1.14 on master
  CHANGELOG.md
Labels: documentation

#61 Handle the case where there are no changes in changelog
  jupyter_releaser/lib.py
Labels: bug

#63 Add missing `return` to `draft_changelog`
  jupyter_releaser/lib.py
  jupyter_releaser/tests/test_functions.py
  setup.cfg
Labels: bug

#64 Automated Changelog Entry for 0.1.15 on master
  CHANGELOG.md
Labels: documentation

#65 Pin versions
  setup.cfg
Labels: bug

#66 Automated Changelog Entry for 0.1.16 on master
  CHANGELOG.md
Labels: documentation

#68 Improve Check Release Isolation
  .github/actions/check-release/action.yml
  jupyter_releaser/actions/draft_release.py
Labels: maintenance

#69 Automated Changelog Entry for 0.1.17 on master
  CHANGELOG.md
Labels: documentation

#70 Add default for `RH_IS_CHECK_RELEASE`
  jupyter_releaser/actions/draft_release.py
Labels: bug

#71 Even more cleanup
  .github/workflows/check-release.yml
  jupyter_releaser/actions/draft_release.py
  jupyter_releaser/lib.py
  jupyter_releaser/util.py
  setup.cfg
Labels: maintenance

#73 Restore guard to pip install if releaser
  jupyter_releaser/actions/draft_release.py
Labels: bug

#74 Automated Changelog Entry for 0.2.1 on master
  CHANGELOG.md
Labels: documentation

#75 Handle commit message failure
  jupyter_releaser/lib.py
Labels: bug

#76 Use Async Output Where Possible
  .github/actions/check-release/action.yml
  LICENSE
  jupyter_releaser/actions/draft_release.py
  jupyter_releaser/tee.py
  jupyter_releaser/util.py
Labels: enhancement

#77 Better Handling of Already Existing Packages
  jupyter_releaser/lib.py
  jupyter_releaser/tests/test_cli.py
Labels: bug

#78 Automated Changelog Entry for 0.2.2 on master
  CHANGELOG.md
Labels: documentation

#79 Fix handling of error output
  jupyter_releaser/lib.py
  jupyter_releaser/tests/test_cli.py
  jupyter_releaser/util.py
Labels: bug

#80 Automated Changelog Entry for 0.2.3 on master
  CHANGELOG.md
Labels: documentation

#82 Fix installing the releaser in the check release workflow
  .github/actions/check-release/action.yml
Labels: bug

#83 Automated Changelog Entry for 0.2.4 on master
  CHANGELOG.md
Labels: documentation

#84 Add ability to skip steps
  README.md
  jupyter_releaser/cli.py
  jupyter_releaser/tests/test_cli.py
  jupyter_releaser/tests/test_functions.py
  jupyter_releaser/util.py
Labels: enhancement

#85 Allow after-prep-git to work
  jupyter_releaser/cli.py
Labels: bug

#86 Add extra changelog check before push
  jupyter_releaser/actions/draft_release.py
Labels: maintenance

#87 Automated Changelog Entry for 0.3.0 on master
  CHANGELOG.md
Labels: documentation

#88 Update check-release.yml
  .github/workflows/check-release.yml
Labels: maintenance

#89 support structured branch name
  .github/actions/check-release/action.yml
Labels: bug

#90 Automated Changelog Entry for 0.3.1 on master
  CHANGELOG.md
Labels: documentation

#91 More Cleanup
  jupyter_releaser/actions/draft_release.py
  jupyter_releaser/changelog.py
  jupyter_releaser/cli.py
  jupyter_releaser/util.py
Labels: maintenance

#92 Automated Changelog Entry for 0.3.2 on master
  CHANGELOG.md
Labels: documentation

#93 Fix Handling of Tag Lock
  jupyter_releaser/actions/draft_release.py
Labels: bug

#94 Automated Changelog Entry for 0.3.3 on master
  CHANGELOG.md
Labels: documentation
