Repository jupyter-server/jupyter_releaser, pull requests merged in 2021-12, with the labels that each got.

#217 Fix missing quote in Draft Changelog
  .github/workflows/draft-changelog.yml
Labels: maintenance

#219 Fix a typo (missing `=`)
  docs/source/how_to_guides/convert_repo.md
Labels: documentation

#220 Beautify rendering of the configuration file list
  docs/source/how_to_guides/write_config.md
Labels: documentation

#221 Add 'next' convenience for tbump
  docs/source/get_started/making_first_release.md
  jupyter_releaser/tests/test_functions.py
  jupyter_releaser/util.py
Labels: enhancement

#223 Make branch and version spec optional
  .github/workflows/draft-changelog.yml
  .github/workflows/draft-release.yml
  .github/workflows/full-release.yml
  .github/workflows/generate-changelog.yml
  .github/workflows/publish-release.yml
  jupyter_releaser/actions/common.py
  jupyter_releaser/actions/generate-changelog.py
  jupyter_releaser/changelog.py
  jupyter_releaser/lib.py
  jupyter_releaser/util.py
Labels: enhancement

#218 Sort the list of workspace package versions
  jupyter_releaser/npm.py
Labels: enhancement

#224 Fix default branch handling and update UX
  .github/actions/draft-release/action.yml
  .github/workflows/draft-changelog.yml
  .github/workflows/draft-release.yml
  .github/workflows/full-release.yml
  jupyter_releaser/actions/draft_changelog.py
  jupyter_releaser/actions/draft_release.py
Labels: bug

#225 Automated Changelog Entry for 0.10.0 on master
  CHANGELOG.md
Labels: documentation

#228 Fix handling of dev version in version bump
  jupyter_releaser/tests/test_functions.py
  jupyter_releaser/util.py
Labels: bug

#229 Automated Changelog Entry for 0.10.1 on master
  CHANGELOG.md
Labels: documentation

#230 Fix handling of empty documentation header
  jupyter_releaser/changelog.py
  jupyter_releaser/tests/util.py
  setup.cfg
Labels: bug

#231 Automated Changelog Entry for 0.10.2 on master
  CHANGELOG.md
Labels: documentation

#233 Update to the new `main` default branch
  .github/workflows/test.yml
  CONTRIBUTING.md
  docs/source/conf.py
  docs/source/how_to_guides/convert_repo.md
Labels: maintenance

#232 Use the last line of the `python setup.py --version` command to get the Python version
  jupyter_releaser/util.py
Labels: enhancement
