Repository jupyter-server/jupyter_releaser, pull requests merged in 2022-05, with the labels that each got.

#308 Fix handling of nested resource files
  .github/workflows/test.yml
  docs/source/how_to_guides/write_config.md
  jupyter_releaser/python.py
  jupyter_releaser/tests/test_cli.py
  setup.cfg
Labels: bug

#312 Automated Changelog Entry for 0.20.0 on main
  CHANGELOG.md
Labels: documentation

#311 Switch to flit
  .flake8
  MANIFEST.in
  pyproject.toml
  setup.cfg
  setup.py
Labels: maintenance

#314 Allow bot PRs to be auto labeled
  .github/workflows/enforce-label.yml
Labels: maintenance

#315 Handle license
  pyproject.toml
Labels: maintenance

#317 Remove dead link
  docs/source/how_to_guides/convert_repo.md
Labels: maintenance

#319 Fix pip install in git checkout
  jupyter_releaser/lib.py
Labels: enhancement

#320 Automated Changelog Entry for 0.21.0 on main
  CHANGELOG.md
Labels: documentation

#322 Check build-system before installing
  jupyter_releaser/lib.py
Labels: bug

#323 Switch to hatch backend
  pyproject.toml
Labels: maintenance

#324 add step N to actions to make it easier
  .github/workflows/draft-changelog.yml
  .github/workflows/full-release.yml
Labels: documentation
