Repository jupyter-server/jupyter_releaser, pull requests merged in 2022-09, with the labels that each got.

#363 Refactor and Simplify Workflows
  .github/actions/check-links/action.yml
  .github/actions/check-release/action.yml
  .github/actions/draft-changelog/action.yml
  .github/actions/draft-release/action.yml
  .github/actions/publish-release/action.yml
  .github/workflows/draft-changelog.yml
  .github/workflows/draft-release.yml
  .github/workflows/full-release.yml
  .github/workflows/publish-release.yml
  .github/workflows/test.yml
  README.md
  docs/source/background/theory.md
  docs/source/get_started/making_first_release.md
  jupyter_releaser/actions/common.py
  jupyter_releaser/actions/draft_changelog.py
  jupyter_releaser/actions/draft_release.py
  jupyter_releaser/actions/publish_release.py
  jupyter_releaser/cli.py
  jupyter_releaser/lib.py
  jupyter_releaser/mock_github.py
  jupyter_releaser/python.py
  jupyter_releaser/tests/conftest.py
  jupyter_releaser/tests/test_cli.py
  jupyter_releaser/tests/test_functions.py
  jupyter_releaser/tests/test_mock_github.py
  jupyter_releaser/tests/util.py
  jupyter_releaser/util.py
Labels: enhancement

#374 Use "hatchling version" as a version command where applicable
  docs/source/conf.py
  jupyter_releaser/util.py
  pyproject.toml
Labels: enhancement

#377 Get repository from release url if given
  jupyter_releaser/util.py
Labels: bug

#378 Fix publish-release
  .github/workflows/full-release.yml
  jupyter_releaser/lib.py
  jupyter_releaser/util.py
Labels: bug

#379 Clean up workflows
  .github/actions/draft-changelog/action.yml
  .github/workflows/draft-changelog.yml
  jupyter_releaser/lib.py
Labels: maintenance

#380 More workflow cleanup
  .github/actions/draft-release/action.yml
  .github/actions/publish-release/action.yml
  .github/workflows/draft-changelog.yml
  .github/workflows/draft-release.yml
  .github/workflows/full-release.yml
  .github/workflows/publish-release.yml
  jupyter_releaser/actions/draft_changelog.py
  jupyter_releaser/changelog.py
  jupyter_releaser/util.py
Labels: maintenance

#381 Do not fetch draft release in check_changelog
  jupyter_releaser/actions/common.py
  jupyter_releaser/actions/draft_changelog.py
  jupyter_releaser/util.py
Labels: bug

#382 Automated Changelog Entry for 0.24.0 on main
  CHANGELOG.md
Labels: documentation

#383 Fix handling of fetch_draft_release param
  jupyter_releaser/actions/common.py
Labels: bug

#386 Automated Changelog Entry for 0.24.1 on main
  CHANGELOG.md
Labels: documentation

#387 Clean up handling of draft release metadata
  jupyter_releaser/cli.py
  jupyter_releaser/util.py
Labels: bug

#389 Use pipx for cli scripts and hatch for hatch version
  jupyter_releaser/cli.py
  jupyter_releaser/lib.py
  jupyter_releaser/python.py
  jupyter_releaser/tests/conftest.py
  jupyter_releaser/tests/test_cli.py
  jupyter_releaser/tests/test_functions.py
  jupyter_releaser/util.py
  pyproject.toml
Labels: maintenance

#391 Automated Changelog Entry for 0.24.2 on main
  CHANGELOG.md
Labels: documentation

#392 Fix handling of check manifest
  jupyter_releaser/cli.py
Labels: bug

#393 Automated Changelog Entry for 0.24.3 on main
  CHANGELOG.md
Labels: documentation

#395 Remove check links and check manifest
  .github/actions/check-links/action.yml
  .github/workflows/test.yml
  README.md
  docs/source/background/theory.md
  docs/source/how_to_guides/write_config.md
  jupyter_releaser/actions/check_links.py
  jupyter_releaser/actions/draft_release.py
  jupyter_releaser/cli.py
  jupyter_releaser/lib.py
  jupyter_releaser/tests/test_cli.py
  pyproject.toml
Labels: maintenance

#396 Clean up Extract Release
  jupyter_releaser/cli.py
  jupyter_releaser/lib.py
  jupyter_releaser/python.py
  jupyter_releaser/tests/test_cli.py
  jupyter_releaser/tests/util.py
  jupyter_releaser/util.py
Labels: enhancement

#397 Simplified Workflow
  .github/actions/check-release/action.yml
  .github/actions/finalize-release/action.yml
  .github/actions/populate-release/action.yml
  .github/actions/prep-release/action.yml
  .github/workflows/draft-release.yml
  .github/workflows/full-release.yml
  .github/workflows/prep-release.yml
  .github/workflows/publish-release.yml
  .github/workflows/test.yml
  jupyter_releaser/actions/common.py
  jupyter_releaser/actions/draft_release.py
  jupyter_releaser/actions/finalize_release.py
  jupyter_releaser/actions/populate_release.py
  jupyter_releaser/actions/prep_release.py
  jupyter_releaser/cli.py
  jupyter_releaser/lib.py
  jupyter_releaser/tests/test_cli.py
  jupyter_releaser/tests/test_functions.py
  jupyter_releaser/util.py
  pyproject.toml
Labels: enhancement

#400 Install the version2 branch in common action
  .github/actions/check-release/action.yml
  .github/actions/install-releaser/action.yml
  .github/actions/populate-release/action.yml
  .github/actions/prep-release/action.yml
Labels: maintenance

#401 Clean up asset sha handling
  .github/workflows/prep-release.yml
  .github/workflows/publish-release.yml
  jupyter_releaser/actions/populate_release.py
  jupyter_releaser/lib.py
  jupyter_releaser/util.py
Labels: bug

#402 Fix handling of asset_shas check
  jupyter_releaser/actions/populate_release.py
Labels: bug

#403 Fix handling of twine repository url
  jupyter_releaser/cli.py
  jupyter_releaser/lib.py
  jupyter_releaser/tests/test_cli.py
Labels: bug

#404 Fix twine repository handling
  jupyter_releaser/cli.py
  jupyter_releaser/lib.py
  jupyter_releaser/tests/test_cli.py
Labels: bug

#405 Fix handling of changelog entry
  jupyter_releaser/actions/populate_release.py
  jupyter_releaser/changelog.py
  jupyter_releaser/cli.py
  jupyter_releaser/lib.py
Labels: bug

#407 Fix default twine registry
  jupyter_releaser/cli.py
Labels: bug

#408 Fix default twine registry
  jupyter_releaser/cli.py
Labels: bug

#410 Fix default twine registry again
  jupyter_releaser/cli.py
Labels: bug

#409 fix default registry again
  jupyter_releaser/cli.py
Labels: bug

#411 Automated Changelog Entry for 0.25.0 on main
  CHANGELOG.md
Labels: documentation

#413 Run mdformat on the manually formatted changelog entry
  .pre-commit-config.yaml
  CHANGELOG.md
  jupyter_releaser/lib.py
  pyproject.toml
Labels: maintenance
