Repository jupyter-server/jupyter_releaser, pull requests merged in 2022-02, with the labels that each got.

#256 Add support for minor release
  .github/workflows/test.yml
  docs/source/get_started/making_first_release.md
  jupyter_releaser/tests/test_functions.py
  jupyter_releaser/util.py
Labels: enhancement

#258 Make twine check strict by default
  jupyter_releaser/cli.py
  jupyter_releaser/lib.py
  jupyter_releaser/python.py
  jupyter_releaser/tests/test_cli.py
Labels: enhancement

#257 Use a more efficient fetch
  jupyter_releaser/lib.py
  jupyter_releaser/tests/test_cli.py
  jupyter_releaser/util.py
Labels: enhancement

#259 Add documentation label to changelog PR
  jupyter_releaser/lib.py
  jupyter_releaser/tests/test_cli.py
  jupyter_releaser/tests/util.py
Labels: enhancement

#260 Automated Changelog Entry for 0.13.0 on main
  CHANGELOG.md
Labels: documentation

#261 Select first commit if there is no tags
  jupyter_releaser/changelog.py
  jupyter_releaser/tests/test_functions.py
  jupyter_releaser/util.py
Labels: bug
