Repository jupyter-server/jupyter_releaser, pull requests merged in 2022-01, with the labels that each got.

#234 Run CI on Python 3.10
  .github/workflows/draft-changelog.yml
  .github/workflows/draft-release.yml
  .github/workflows/full-release.yml
  .github/workflows/generate-changelog.yml
  .github/workflows/test.yml
  docs/environment.yml
  setup.cfg
Labels: maintenance

#236 Update generate-changelog test
  .github/workflows/test.yml
Labels: maintenance

#238 Add configurable python target to check-python
  jupyter_releaser/cli.py
  jupyter_releaser/python.py
  jupyter_releaser/tests/conftest.py
  jupyter_releaser/tests/test_cli.py
  jupyter_releaser/tests/util.py
Labels: bug, enhancement

#239 Skip doctests when checking links
  jupyter_releaser/lib.py
Labels: bug

#240 Automated Changelog Entry for 0.11.0 on main
  CHANGELOG.md
Labels: documentation

#241 Fix handling of doctest skip
  jupyter_releaser/lib.py
Labels: bug

#242 Automated Changelog Entry for 0.11.1 on main
  CHANGELOG.md
Labels: documentation

#243 Test empty changelog
  jupyter_releaser/changelog.py
  jupyter_releaser/tests/test_functions.py
  jupyter_releaser/tests/util.py
Labels: bug

#245 Automated Changelog Entry for 0.11.2 on main
  CHANGELOG.md
Labels: documentation

#246 ignore package pytest config
  jupyter_releaser/lib.py
Labels: enhancement

#248 Automated Changelog Entry for 0.11.3 on main
  CHANGELOG.md
Labels: documentation

#252 Update to `tbump~=6.7`
  setup.cfg
Labels: maintenance

#251 Update `setuptools`
  setup.cfg
Labels: maintenance

#253 Automated Changelog Entry for 0.12.0 on main
  CHANGELOG.md
Labels: documentation
