Repository jupyter-server/jupyter_releaser, pull requests merged in 2022-10, with the labels that each got.

#414 Update docs for simplified workflow
  .github/workflows/prep-release.yml
  .github/workflows/publish-release.yml
  README.md
  docs/source/background/theory.md
  docs/source/get_started/index.rst
  docs/source/get_started/making_release_from_releaser.md
  docs/source/get_started/making_release_from_repo.md
  docs/source/how_to_guides/convert_repo_from_releaser.md
  docs/source/how_to_guides/convert_repo_from_repo.md
  docs/source/how_to_guides/index.rst
Labels: documentation

#415 Merge v2 into main
  .github/actions/check-links/action.yml
  .github/actions/check-release/action.yml
  .github/actions/finalize-release/action.yml
  .github/actions/install-releaser/action.yml
  .github/actions/populate-release/action.yml
  .github/actions/prep-release/action.yml
  .github/scripts/bump_tag.sh
  .github/workflows/draft-release.yml
  .github/workflows/full-release.yml
  .github/workflows/prep-release.yml
  .github/workflows/publish-release.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  CHANGELOG.md
  README.md
  docs/source/background/theory.md
  docs/source/get_started/index.rst
  docs/source/get_started/making_release_from_releaser.md
  docs/source/get_started/making_release_from_repo.md
  docs/source/how_to_guides/convert_repo_from_releaser.md
  docs/source/how_to_guides/convert_repo_from_repo.md
  docs/source/how_to_guides/index.rst
  docs/source/how_to_guides/write_config.md
  jupyter_releaser/actions/check_links.py
  jupyter_releaser/actions/common.py
  jupyter_releaser/actions/draft_release.py
  jupyter_releaser/actions/finalize_release.py
  jupyter_releaser/actions/populate_release.py
  jupyter_releaser/actions/prep_release.py
  jupyter_releaser/changelog.py
  jupyter_releaser/cli.py
  jupyter_releaser/lib.py
  jupyter_releaser/python.py
  jupyter_releaser/tests/test_cli.py
  jupyter_releaser/tests/test_functions.py
  jupyter_releaser/tests/util.py
  jupyter_releaser/util.py
  pyproject.toml
Labels: maintenance

#417 Fix action targets
  .github/actions/check-release/action.yml
  .github/actions/install-releaser/action.yml
  .github/actions/populate-release/action.yml
  .github/actions/prep-release/action.yml
  .github/workflows/prep-release.yml
  .github/workflows/publish-release.yml
Labels: maintenance

#418 Another workflow fix
  .github/workflows/publish-release.yml
Labels: bug

#419 Switch to v2 tag
  .github/actions/check-release/action.yml
  .github/actions/install-releaser/action.yml
  .github/actions/populate-release/action.yml
  .github/actions/prep-release/action.yml
  .github/workflows/prep-release.yml
  .github/workflows/publish-release.yml
Labels: maintenance

#422 Add more debugging to ensure_sha
  jupyter_releaser/util.py
Labels: bug

#425 Revert "Better handling of git actor"
  .github/workflows/prep-release.yml
  .github/workflows/publish-release.yml
  README.md
  docs/source/how_to_guides/convert_repo_from_repo.md
  jupyter_releaser/lib.py
  jupyter_releaser/tests/test_cli.py
  jupyter_releaser/util.py
Labels: bug

#426 Stop erroring on ensure_sha for now
  jupyter_releaser/util.py
Labels: bug

#427 Fix ensure_sha
  README.md
  jupyter_releaser/actions/populate_release.py
  jupyter_releaser/util.py
Labels: bug

#430 Try fixing admin handling
  jupyter_releaser/util.py
Labels: bug

#431 Use admin token
  .github/workflows/prep-release.yml
  .github/workflows/publish-release.yml
  docs/source/how_to_guides/convert_repo_from_repo.md
Labels: bug

#432 Use global hatch if available
  jupyter_releaser/util.py
Labels: maintenance

#435 Fix handling of ensure sha
  jupyter_releaser/actions/populate_release.py
  jupyter_releaser/cli.py
  jupyter_releaser/lib.py
  jupyter_releaser/tests/test_cli.py
  jupyter_releaser/util.py
Labels: bug

#437 Allow dev versions
  .github/workflows/check-release.yml
  .github/workflows/test.yml
  jupyter_releaser/__init__.py
  jupyter_releaser/changelog.py
  jupyter_releaser/cli.py
  jupyter_releaser/lib.py
  jupyter_releaser/tests/test_functions.py
  jupyter_releaser/util.py
  pyproject.toml
Labels: bug

#442 Update handling of action outputs
  jupyter_releaser/util.py
Labels: maintenance

#436 Use hatch envs and clean up workflows
  .github/actions/common/action.yml
  .github/workflows/check-release.yml
  .github/workflows/generate-changelog.yml
  .github/workflows/prep-release.yml
  .github/workflows/publish-release.yml
  .github/workflows/test.yml
  docs/environment.yml
  docs/source/background/theory.md
  docs/source/how_to_guides/convert_repo_from_releaser.md
  docs/source/how_to_guides/convert_repo_from_repo.md
  jupyter_releaser/util.py
  pyproject.toml
  readthedocs.yml
Labels: maintenance

#443 Update how-to guides
  docs/source/how_to_guides/convert_repo_from_releaser.md
  docs/source/how_to_guides/convert_repo_from_repo.md
  example-workflows/prep-release.yml
  example-workflows/publish-release.yml
Labels: documentation

#444 Fix variable name for GitHub output
  .github/workflows/test.yml
  jupyter_releaser/util.py
Labels: bug

#445 Improve test speed
  .github/workflows/test.yml
  jupyter_releaser/lib.py
  jupyter_releaser/mock_github.py
  jupyter_releaser/python.py
  jupyter_releaser/tests/conftest.py
  jupyter_releaser/tests/test_cli.py
  jupyter_releaser/util.py
  pyproject.toml
Labels: maintenance

#446 Update screenshots for Version 2
  docs/source/get_started/making_release_from_releaser.md
  docs/source/get_started/making_release_from_repo.md
  docs/source/images/draft_changelog.png
  docs/source/images/draft_changelog_next_step.png
  docs/source/images/draft_changelog_pr.png
  docs/source/images/draft_github_release.png
  docs/source/images/draft_release.png
  docs/source/images/draft_release_next_step.png
  docs/source/images/prep_release.png
  docs/source/images/prep_release_next_step.png
  docs/source/images/prep_release_repo.png
  docs/source/images/publish_release.png
  docs/source/images/publish_release_next_step.png
  docs/source/images/publish_release_repo.png
Labels: documentation

#447 Remove flake8 file
  .flake8
  .pre-commit-config.yaml
  pyproject.toml
Labels: maintenance

#449 Do no install the package by default
  jupyter_releaser/lib.py
Labels: bug

#450 Update conversion instructions
  docs/source/how_to_guides/convert_repo_from_repo.md
Labels: documentation

#451 Fix handling of `GITHUB_OUTPUT`
  jupyter_releaser/util.py
Labels: bug

#454 Add docs for starting making prereleases
  docs/source/get_started/making_release_from_repo.md
Labels: documentation

#457 Maintenance cleanup
  .github/workflows/test.yml
  .pre-commit-config.yaml
  docs/source/get_started/making_release_from_releaser.md
  docs/source/get_started/making_release_from_repo.md
  docs/source/how_to_guides/convert_repo_from_releaser.md
  docs/source/how_to_guides/convert_repo_from_repo.md
  pyproject.toml
Labels: maintenance
