Repository jupyter-server/jupyter_releaser, pull requests merged in 2022-04, with the labels that each got.

#281 Fix listing of tags
  jupyter_releaser/lib.py
Labels: bug

#282 Fix check_links on macOS
  jupyter_releaser/lib.py
Labels: bug

#283 Automated Changelog Entry for 0.15.0 on main
  CHANGELOG.md
Labels: documentation

#284 Use setup.py --version by default
  jupyter_releaser/util.py
Labels: bug

#285 Automated Changelog Entry for 0.15.1 on main
  CHANGELOG.md
Labels: documentation

#287 Improve handling of dev versions
  README.md
  docs/source/background/theory.md
  docs/source/how_to_guides/write_config.md
  jupyter_releaser/changelog.py
  jupyter_releaser/cli.py
  jupyter_releaser/lib.py
  jupyter_releaser/tests/test_functions.py
  jupyter_releaser/util.py
Labels: enhancement

#289 Clean up check links output
  jupyter_releaser/lib.py
  jupyter_releaser/tee.py
  jupyter_releaser/util.py
Labels: maintenance

#288 Use print groups and input types
  .github/workflows/draft-changelog.yml
  .github/workflows/draft-release.yml
  .github/workflows/full-release.yml
  .github/workflows/generate-changelog.yml
  jupyter_releaser/actions/check_links.py
  jupyter_releaser/actions/common.py
  jupyter_releaser/actions/draft_changelog.py
  jupyter_releaser/actions/draft_release.py
  jupyter_releaser/actions/generate-changelog.py
  jupyter_releaser/actions/publish_release.py
Labels: enhancement

#290 Automated Changelog Entry for 0.16.0 on main
  CHANGELOG.md
Labels: documentation

#291 Fix docs on config values
  docs/source/how_to_guides/write_config.md
Labels: documentation

#292 Update check-links and settings
  jupyter_releaser/lib.py
  setup.cfg
Labels: maintenance

#293 Automated Changelog Entry for 0.17.0 on main
  CHANGELOG.md
Labels: documentation

#295 Clean up pre-commit
  .github/workflows/test.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  jupyter_releaser/actions/check_links.py
  jupyter_releaser/actions/draft_changelog.py
  jupyter_releaser/actions/draft_release.py
  jupyter_releaser/actions/generate-changelog.py
  jupyter_releaser/changelog.py
  jupyter_releaser/cli.py
  jupyter_releaser/lib.py
  jupyter_releaser/python.py
  jupyter_releaser/tee.py
  jupyter_releaser/tests/conftest.py
  jupyter_releaser/tests/test_cli.py
  jupyter_releaser/tests/test_functions.py
  jupyter_releaser/tests/util.py
  jupyter_releaser/util.py
  setup.cfg
Labels: maintenance

#298 Add ability to splice github release entry
  jupyter_releaser/changelog.py
  jupyter_releaser/tests/test_functions.py
  jupyter_releaser/tests/util.py
Labels: enhancement

#300 Clean up pytest and add mypy handling
  .github/workflows/draft-changelog.yml
  .github/workflows/draft-release.yml
  .github/workflows/full-release.yml
  .github/workflows/generate-changelog.yml
  .github/workflows/publish-release.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  MANIFEST.in
  docs/source/conf.py
  jupyter_releaser/actions/draft_changelog.py
  jupyter_releaser/actions/draft_release.py
  jupyter_releaser/cli.py
  jupyter_releaser/lib.py
  jupyter_releaser/npm.py
  jupyter_releaser/py.typed
  jupyter_releaser/python.py
  jupyter_releaser/tee.py
  jupyter_releaser/tests/conftest.py
  jupyter_releaser/tests/test_cli.py
  jupyter_releaser/tests/test_functions.py
  jupyter_releaser/tests/util.py
  jupyter_releaser/util.py
  pyproject.toml
  setup.py
Labels: maintenance

#301 Add a utility to get the latest draft release for a given repo
  jupyter_releaser/tests/test_functions.py
  jupyter_releaser/tests/util.py
  jupyter_releaser/util.py
Labels: enhancement

#302 Only run check-manifest if using setuptools
  jupyter_releaser/cli.py
  jupyter_releaser/util.py
Labels: bug

#303 Handle manual backport PRs
  jupyter_releaser/changelog.py
  jupyter_releaser/tests/test_cli.py
Labels: enhancement

#304 Automated Changelog Entry for 0.18.0 on main
  CHANGELOG.md
Labels: documentation

#306 Add handling of pydist resource paths
  .github/workflows/test.yml
  docs/source/how_to_guides/write_config.md
  jupyter_releaser/cli.py
  jupyter_releaser/lib.py
  jupyter_releaser/python.py
  jupyter_releaser/tests/test_cli.py
Labels: enhancement

#307 Automated Changelog Entry for 0.19.0 on main
  CHANGELOG.md
Labels: documentation
