Repository jupyter-server/jupyter_releaser, pull requests merged in 2022-12, with the labels that each got.

#471 Adopt ruff and address lint
  .github/dependabot.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  jupyter_releaser/lib.py
  jupyter_releaser/tests/test_cli.py
  jupyter_releaser/tests/test_functions.py
  jupyter_releaser/util.py
  pyproject.toml
Labels: maintenance

#473 Fix handling of dev mode
  jupyter_releaser/tests/test_cli.py
  jupyter_releaser/tests/test_functions.py
  jupyter_releaser/tests/util.py
  jupyter_releaser/util.py
Labels: bug

#475 Add log when loading configuration
  jupyter_releaser/util.py
Labels: maintenance

#476 Fix typo 1
  docs/source/how_to_guides/convert_repo_from_repo.md
Labels: documentation

#477 Fix typo(?) 2
  docs/source/how_to_guides/convert_repo_from_releaser.md
Labels: documentation

#478 ci cleanup
  .github/workflows/test.yml
  .pre-commit-config.yaml
  pyproject.toml
Labels: maintenance

#481 Add more default python dist checks
  .github/workflows/test.yml
  jupyter_releaser/actions/generate_changelog.py
  jupyter_releaser/cli.py
  jupyter_releaser/python.py
  jupyter_releaser/tee.py
  jupyter_releaser/tests/test_cli.py
Labels: enhancement

#482 Add since_last_stable support in generate changelog
  .github/workflows/generate-changelog.yml
  jupyter_releaser/actions/generate_changelog.py
  jupyter_releaser/util.py
Labels: enhancement

#483 Use pyproject.toml for config in check-wheel-contents
  jupyter_releaser/cli.py
Labels: bug

#484 Add spell checking and enforce docstrings
  .github/workflows/test.yml
  .pre-commit-config.yaml
  docs/source/conf.py
  jupyter_releaser/__main__.py
  jupyter_releaser/actions/common.py
  jupyter_releaser/actions/finalize_release.py
  jupyter_releaser/actions/generate_changelog.py
  jupyter_releaser/actions/populate_release.py
  jupyter_releaser/actions/prep_release.py
  jupyter_releaser/changelog.py
  jupyter_releaser/cli.py
  jupyter_releaser/lib.py
  jupyter_releaser/mock_github.py
  jupyter_releaser/npm.py
  jupyter_releaser/python.py
  jupyter_releaser/util.py
  pyproject.toml
Labels: maintenance

#485 Enable tasklist myst extension
  docs/source/conf.py
Labels: documentation
