Repository jupyter-server/jupyter_releaser, pull requests merged in 2022-03, with the labels that each got.

#262 Create forwardport PR after publishing
  jupyter_releaser/actions/publish_release.py
Labels: bug

#263 Automated Changelog Entry for 0.13.1 on main
  CHANGELOG.md
Labels: documentation

#265 Forwardport changelog before publishing github release
  jupyter_releaser/actions/publish_release.py
Labels: bug

#266 Automated Changelog Entry for 0.13.2 on main
  CHANGELOG.md
Labels: documentation

#268 forward python imports for checking with extract_release
  jupyter_releaser/cli.py
  jupyter_releaser/lib.py
Labels: bug

#270 Include explicit package data
  .github/workflows/test.yml
  setup.cfg
Labels: bug

#271 Automated Changelog Entry for 0.13.3 on main
  CHANGELOG.md
Labels: documentation

#275 Support static version in pyproject.toml
  .pre-commit-config.yaml
  jupyter_releaser/tee.py
  jupyter_releaser/tests/test_functions.py
  jupyter_releaser/tests/util.py
  jupyter_releaser/util.py
Labels: enhancement

#276 Automated Changelog Entry for 0.14.0 on main
  CHANGELOG.md
Labels: documentation
