Repository jupyter-server/jupyter_releaser, pull requests merged in 2022-08, with the labels that each got.

#352 Add mock github api
  .pre-commit-config.yaml
  jupyter_releaser/mock_github.py
  jupyter_releaser/tests/conftest.py
  jupyter_releaser/tests/test_cli.py
  jupyter_releaser/tests/test_functions.py
  jupyter_releaser/tests/test_mock_github.py
  jupyter_releaser/tests/util.py
  jupyter_releaser/util.py
  pyproject.toml
Labels: enhancement

#354 Fix flake8 v5 compat
  .pre-commit-config.yaml
Labels: maintenance

#355 Use mock github when in dry run mode
  jupyter_releaser/actions/common.py
  jupyter_releaser/changelog.py
  jupyter_releaser/cli.py
  jupyter_releaser/lib.py
  jupyter_releaser/mock_github.py
  jupyter_releaser/tests/conftest.py
  jupyter_releaser/util.py
Labels: enhancement

#356 Use bare git for dry run
  jupyter_releaser/lib.py
  jupyter_releaser/util.py
Labels: enhancement

#357 Highlight next step using GitHub step summary
  .github/workflows/draft-changelog.yml
  .github/workflows/draft-release.yml
  .github/workflows/full-release.yml
  .github/workflows/publish-release.yml
Labels: enhancement

#358 Automated Changelog Entry for 0.23.0 on main
  CHANGELOG.md
  jupyter_releaser/lib.py
Labels: documentation

#360 Revert to using stash apply instead of merge
  jupyter_releaser/lib.py
Labels: bug

#361 Automated Changelog Entry for 0.23.1 on main
  CHANGELOG.md
Labels: documentation

#362 Fix changelog pr for dry run
  jupyter_releaser/lib.py
Labels: bug

#364 Revert changes to make changelog pr
  jupyter_releaser/cli.py
  jupyter_releaser/lib.py
  jupyter_releaser/tests/test_cli.py
  jupyter_releaser/tests/util.py
Labels: bug

#365 Automated Changelog Entry for 0.23.2 on main
  CHANGELOG.md
Labels: documentation

#366 Fix the input parameter since_last_stable when running a full release
  .github/workflows/full-release.yml
  pyproject.toml
Labels: bug

#368 Automated Changelog Entry for 0.23.3 on main
  CHANGELOG.md
Labels: documentation
