Repository jupyter-server/jupyter_releaser, pull requests merged in 2023-12, with the labels that each got.

#538 Remove unneeded token from workflow inputs
  .github/workflows/publish-changelog.yml
  example-workflows/publish-changelog.yml
Labels: bug

#539 Add test for repository.url
  jupyter_releaser/cli.py
  jupyter_releaser/npm.py
  jupyter_releaser/tests/conftest.py
  jupyter_releaser/tests/util.py
Labels: bug

#541 Fix string repository
  jupyter_releaser/npm.py
Labels: bug

#542 Update ruff config
  .github/workflows/test.yml
  .pre-commit-config.yaml
  docs/source/conf.py
  jupyter_releaser/changelog.py
  jupyter_releaser/cli.py
  jupyter_releaser/lib.py
  jupyter_releaser/mock_github.py
  jupyter_releaser/npm.py
  jupyter_releaser/python.py
  jupyter_releaser/tee.py
  jupyter_releaser/util.py
  pyproject.toml
  tests/__init__.py
  tests/conftest.py
  tests/test_changelog.py
  tests/test_cli.py
  tests/test_functions.py
  tests/test_mock_github.py
  tests/util.py
Labels: maintenance

#544 Add trusted publishing and self release
  .github/workflows/prep-self-release.yml
  .github/workflows/publish-self-release.yml
Labels: enhancement
