Repository jupyter-server/jupyter_releaser, pull requests merged in 2023-01, with the labels that each got.

#488 Sync lint deps
  pyproject.toml
Labels: maintenance

#489 Pass the authentication to `format_pr_entry`
  jupyter_releaser/changelog.py
  jupyter_releaser/lib.py
Labels: bug

#491 Add whitelist for http request in yarn
  .github/actions/check-release/action.yml
Labels: enhancement

#492 Add more linting
  .pre-commit-config.yaml
  docs/source/conf.py
  jupyter_releaser/actions/populate_release.py
  jupyter_releaser/changelog.py
  jupyter_releaser/cli.py
  jupyter_releaser/lib.py
  jupyter_releaser/mock_github.py
  jupyter_releaser/npm.py
  jupyter_releaser/python.py
  jupyter_releaser/tee.py
  jupyter_releaser/tests/test_cli.py
  jupyter_releaser/tests/test_mock_github.py
  jupyter_releaser/tests/util.py
  jupyter_releaser/util.py
  pyproject.toml
Labels: maintenance
