Repository jupyter-server/jupyter_releaser, pull requests merged in 2023-06, with the labels that each got.

#512 Pin ghapi
  pyproject.toml
Labels: maintenance

#511 Add support for PyPI trusted publisher and NPM provenance
  docs/source/get_started/making_release_from_releaser.md
  docs/source/how_to_guides/convert_repo_from_releaser.md
  docs/source/how_to_guides/convert_repo_from_repo.md
  example-workflows/full-release.yml
  example-workflows/publish-release.yml
  jupyter_releaser/lib.py
  jupyter_releaser/npm.py
  jupyter_releaser/python.py
  jupyter_releaser/util.py
Labels: enhancement

#514 Fix package version target
  .github/actions/finalize-release/action.yml
Labels: bug

#515 Fix doc edition links
  docs/source/conf.py
Labels: documentation
