Repository jupyter-server/jupyter_releaser, pull requests merged in 2024-03, with the labels that each got.

#559 Add ability to disable admin user check via flag
  .github/actions/check-release/action.yml
  .github/actions/finalize-release/action.yml
  .github/actions/populate-release/action.yml
  .github/actions/prep-release/action.yml
  .github/actions/publish-changelog/action.yml
  jupyter_releaser/util.py
Labels: enhancement

#557 Remove the need for an ADMIN_GITHUB_TOKEN
  .github/workflows/prep-self-release.yml
  .github/workflows/publish-changelog.yml
  .github/workflows/publish-self-release.yml
  docs/source/background/theory.md
  docs/source/how_to_guides/convert_repo_from_repo.md
  docs/source/how_to_guides/maintain_fork.md
  example-workflows/full-release.yml
  example-workflows/prep-release.yml
  example-workflows/publish-changelog.yml
  example-workflows/publish-release.yml
Labels: enhancement

#560 Remove unused input in prep release example
  example-workflows/prep-release.yml
Labels: maintenance

#561 Update Getting Started Guide
  docs/source/get_started/making_release_from_repo.md
Labels: documentation

#562 Do not require admin for publish changelog action
  .github/actions/publish-changelog/action.yml
Labels: bug

#564 Print out error for npm upload
  jupyter_releaser/lib.py
Labels: bug
