Repository jupyter-server/jupyter_releaser, pull requests merged in 2024-04, with the labels that each got.

#565 Set all min deps
  .github/workflows/test.yml
  pyproject.toml
Labels: maintenance

#568 Normalise package name before comparison
  jupyter_releaser/lib.py
Labels: bug

#570 Prepend tag with Python package name if multiple packages are defined
  jupyter_releaser/cli.py
  jupyter_releaser/lib.py
Labels: bug

#569 Improve documentation
  docs/source/get_started/making_release_from_repo.md
  docs/source/how_to_guides/convert_repo_from_repo.md
Labels: documentation

#572 Fix `maxsplit` usage
  jupyter_releaser/cli.py
Labels: bug
